# Generated by Django 2.2.1 on 2019-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('genre', models.CharField(choices=[('힙합', '힙합'), ('발라드', '발라드'), ('팝송', '팝송'), ('R&B', 'R&B'), ('댄스', '댄스'), ('락', '락')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
